export const data = [
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Rohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 4.5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Sohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 3.5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Bhai Dhaba",
    cuisines: "Momos,Nepal",
    rating: 2.5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Behen Dhaba",
    cuisines: "Momos,Nepal",
    rating: 1.5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Chor Dhaba",
    cuisines: "Momos,Nepal",
    rating: 1.8,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Delhi Dhaba",
    cuisines: "Momos,Nepal",
    rating: 2.9,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 4.9,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 5,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 1.8,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 3.2,
    time: "10 minutes",
  },
  {
    imgUrl: require("../../assets/momos.jpg"),
    name: "Mohan Dhaba",
    cuisines: "Momos,Nepal",
    rating: 4.2,
    time: "10 minutes",
  },
];
